test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, self.words))
  File "/home/runner/work/c02-ch2-majuscule-daveringu/c02-ch2-majuscule-daveringu/exercice.py", line 8, in majuscule
    resultat += cho(lettre)
NameError: name 'cho' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
